### PR TITLE
Replace the font icons to SVG icons, UI file organization and put the Website UI in the marketing folder

### PR DESCRIPTION
**Pull request by thiagotomasi**
@jglovier I made some changes in the files and in the folders. I think this, like a begin of to the style guide, please feel free to change if you want!

### CODE REVIEW

**Comment by thiagotomasi** [comment]
@jglovier I made some changes in the files and in the folder, please fill free to change if you want!

**Comment by jglovier** [comment]
@thiagotomasi I'm sorry but we may have had some miscommunication. When I said it was on my list to replace the font with SVG, I meant in the app, not in the Sketch file. 😊 My apologies if that was not clear.

For now, I'm just using this sketch document as my workspace, so I'd prefer to not make any changes to it outside of my current flow. Eventually I'd like to get to a point where we have a master  HospitalRun UI template Sketch file for anyone to jump in and start using, but I'm still working out a lot of the fundamentals of the app design so it's a bit premature to try to tackle that just yet.

But thanks for the PR! :heart: I'll keep you posted as I get to a spot with the design systems work where I could use contributor help.

**Comment by thiagotomasi** [comment]
@jglovier hoooo, totally my fault!!!! 😄 
I got too excited about the project and I misunderstood what you said!
Just give me a heads up when you need any help! 😄

**Comment by jglovier** [comment]
@thiagotomasi no worries! Glad you are excited. I will def ping you as soon as I have a more clearly defined task you could jump on. :zap:

**Pull request closed without merging**
